const $=id=>document.getElementById(id);
const demos=[...DEMOS.filter(d=>d.group==='Исследование'),...DEMOS.filter(d=>d.id.startsWith('story-')&&d.group!=='Исследование'),...DEMOS.filter(d=>d.id.startsWith('chart-')),...DEMOS.filter(d=>!d.id.startsWith('story-')&&!d.id.startsWith('chart-'))];
const groups=['Все примеры','Исследование','Сложные сцены','Цифры','Графики','Интерактивные графики','Ядро','Прокрутка','Текст','SVG','Интерфейс','Физика и графика','Кривые и разработка'];
let group='Исследование',speed=1,shown=[],codeDemo,codeTab='js',cssText='',reactText='',previewFrame=null,previewDemo=null;
const state=new Map();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
$('total').textContent=demos.length;
function send(s,action,value){if(s?.frame?.contentWindow)s.frame.contentWindow.postMessage({action,value},location.origin);}
function load(s){if(s.frame)return;const frame=document.createElement('iframe');frame.title=s.demo.title;frame.src='demo.html?id='+encodeURIComponent(s.demo.id)+'&compact=1';s.wrap.appendChild(frame);s.frame=frame;s.ready=false;}
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{const s=state.get(entry.target.dataset.id);if(!s)return;s.visible=entry.isIntersecting;if(s.visible){load(s);if(s.ready){send(s,'unfreeze');if(!s.played&&!reduced){send(s,'play');s.played=true;}}}else if(s.ready)send(s,'freeze');});},{threshold:.15});
function render(){observer.disconnect();state.clear();const query=$('search').value.trim().toLowerCase();shown=demos.filter(d=>(group==='Все примеры'||d.group===group)&&[d.title,d.group,d.use,d.hint,...d.plugins].join(' ').toLowerCase().includes(query));$('results').textContent=`${shown.length} из ${demos.length} примеров`;$('filters').innerHTML=groups.map(g=>`<button class="filter ${g===group?'active':''}" aria-pressed="${g===group}" data-group="${g}">${g}</button>`).join('');$('gallery').innerHTML=shown.length?shown.map(d=>`<article class="card ${d.id.startsWith('story-')?'story':''}" data-id="${d.id}"><div class="card-head"><div class="card-meta"><span>${d.group}</span><span class="number">${String(demos.indexOf(d)+1).padStart(2,'0')}</span></div><h2>${d.title}</h2></div><div class="demo-wrap"><div class="waiting">Подготовка примера…</div></div><div class="card-body"><p class="hint">${d.hint}</p><p class="use"><b>Где использовать:</b> ${d.use}</p><div class="actions"><button class="play" data-action="play">Повторить</button><button data-action="reset">Сброс</button>${d.id.startsWith('story-')?'<button data-action="expand">Крупно</button>':''}<button data-action="code">Код</button></div></div></article>`).join(''):'<div class="empty">Совпадений нет. Попробуйте «линия», «счётчик», «текст» или другую категорию.</div>';shown.forEach(d=>{const card=document.querySelector(`[data-id="${d.id}"]`),wrap=card.querySelector('.demo-wrap');const s={demo:d,card,wrap,frame:null,ready:false,visible:false,played:false};state.set(d.id,s);observer.observe(card);});}
$('filters').onclick=e=>{if(e.target.dataset.group){group=e.target.dataset.group;render();}};$('search').oninput=render;
$('speed').onchange=e=>{speed=+e.target.value;state.forEach(s=>send(s,'speed',speed));};
$('replay-visible').onclick=()=>state.forEach(s=>{if(s.visible){load(s);if(s.ready){send(s,'play');s.played=true;}else s.pendingPlay=true;}});
$('gallery').onclick=e=>{const action=e.target.dataset.action,card=e.target.closest('.card');if(!action||!card)return;const s=state.get(card.dataset.id);if(action==='expand'){openPreview(s.demo);return;}if(action==='code'){codeDemo=s.demo;codeTab='js';showCode();$('code-dialog').showModal();return;}if(action==='reset'){if(s.frame)s.frame.remove();s.frame=null;s.ready=false;s.played=true;s.card.classList.remove('error');const waiting=document.createElement('div');waiting.className='waiting';waiting.textContent='Подготовка примера…';s.wrap.replaceChildren(waiting);load(s);return;}load(s);if(s.ready){send(s,'play');s.played=true;}else s.pendingPlay=true;};
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;const s=state.get(e.data?.id);if(!s||e.source!==s.frame?.contentWindow)return;if(e.data.type==='demo-ready'){s.ready=true;s.wrap.querySelector('.waiting')?.remove();send(s,'speed',speed);if(s.pendingPlay||s.visible&&!s.played&&!reduced){send(s,'play');s.played=true;s.pendingPlay=false;}if(!s.visible)send(s,'freeze');}else if(e.data.type==='demo-height'&&s.demo.id.startsWith('story-')){s.wrap.style.height=Math.max(280,Math.min(650,Number(e.data.height)))+'px';}else if(e.data.type==='demo-error'){s.card.classList.add('error');let waiting=s.wrap.querySelector('.waiting');if(!waiting){waiting=document.createElement('div');waiting.className='waiting';s.wrap.appendChild(waiting);}waiting.textContent='Пример не запустился. Нажмите «Сброс», чтобы повторить.';console.error(s.demo.id,e.data.message);}});
function sourceJS(d){if(d.id==='react')return reactText||'Загрузка исходника React…';const imports=['gsap',...d.plugins.map(p=>({'@pixi':'pixi','@easel':'easeljs','@react':'react-demo'}[p]||p))].map(p=>`// Библиотека: vendor/${p}.min.js`).join('\n');const helper='const q = s => document.querySelector(s);\nconst qa = s => [...document.querySelectorAll(s)];\n// Кнопка .play запускает созданную анимацию.\nfunction wire(animation) {\n  window.demoAnimation = animation;\n  document.querySelector(".play").onclick = () => animation.restart();\n  const seek = document.querySelector(".scene-seek");\n  if (seek) {\n    const oldUpdate = animation.eventCallback("onUpdate");\n    animation.eventCallback("onUpdate", () => {\n      if (oldUpdate) oldUpdate.call(animation);\n      seek.value = animation.progress();\n    });\n    seek.oninput = e => animation.progress(+e.target.value).pause();\n  }\n  document.querySelector(".local-play")?.addEventListener("click", () => animation.restart());\n  document.querySelector(".local-pause")?.addEventListener("click", () => animation.pause());\n}\n';return '// Подключение библиотек:\n'+imports+'\n\n'+(d.plugins.filter(p=>!p.startsWith('@')).length?'gsap.registerPlugin('+d.plugins.filter(p=>!p.startsWith('@')).join(', ')+');\n\n':'')+helper+'\n('+d.run.toString()+')();\nif (window.demoPlay) {\n  document.querySelector(".play").onclick = window.demoPlay;\n}\n\n// В интерактивных сценах demoPlay() запускает демонстрационное действие.\n// Основные действия привязаны к кнопкам, жестам и ползункам сцены.';}
function showCode(){if(!codeDemo)return;$('code-title').textContent=codeDemo.title;$('docs').href=codeDemo.doc;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===codeTab));$('source').textContent=codeTab==='js'?sourceJS(codeDemo):codeTab==='html'?'<link rel="stylesheet" href="brand-fonts.css">\n<link rel="stylesheet" href="demo.css">\n<link rel="stylesheet" href="brand-demos.css">\n'+['gsap',...codeDemo.plugins.map(p=>({'@pixi':'pixi','@easel':'easeljs','@react':'react-demo'}[p]||p))].map(p=>'<script src="vendor/'+p+(p==='react-demo'?'.js':'.min.js')+'"><\/script>').join('\n')+'\n<main id="scene">\n'+codeDemo.html+'\n</main>\n<button class="play">Запустить</button>':cssText||'Загрузка стилей…';$('code-note').textContent=codeTab==='js'?'Это код, который выполняется в карточке. Разметка и стили — в соседних вкладках.':'Разметка и общие стили живых примеров.';}
document.querySelector('.code-tabs').onclick=e=>{if(e.target.dataset.tab){codeTab=e.target.dataset.tab;showCode();}};$('close-code').onclick=()=>$('code-dialog').close();$('code-dialog').onclick=e=>{if(e.target===$('code-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('source').textContent);$('copy').textContent='Скопировано';setTimeout(()=>$('copy').textContent='Копировать',1500);}catch{$('code-note').textContent='Выделите код и скопируйте его вручную.';}};
Promise.all([Promise.all(['brand-fonts.css','demo.css','brand-demos.css'].map(path=>fetch(path).then(r=>r.text()))).then(parts=>parts.join('\n')),fetch('react-example.txt').then(r=>r.text())]).then(([css,react])=>{cssText=css;reactText=react;showCode();});render();

function openPreview(demo){previewDemo=demo;previewFrame=document.createElement('iframe');previewFrame.title=demo.title;previewFrame.src='demo.html?id='+encodeURIComponent(demo.id);$('preview-title').textContent=demo.title;$('preview-frame').replaceChildren(previewFrame);$('preview-dialog').showModal();state.forEach(s=>send(s,'freeze'));}
$('close-preview').onclick=()=>$('preview-dialog').close();$('preview-dialog').addEventListener('close',()=>{$('preview-frame').replaceChildren();previewFrame=null;previewDemo=null;state.forEach(s=>{if(s.visible)send(s,'unfreeze');});});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==previewFrame?.contentWindow)return;if(e.data.type==='demo-ready'){previewFrame.contentWindow.postMessage({action:'speed',value:speed},location.origin);if(!reduced)previewFrame.contentWindow.postMessage({action:'play'},location.origin);}});
